// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMRvCSBe1qjJ1bGMxoHqD1M572lDQ_x4w',
    appId: '1:1099105297287:web:544b5af3ac0acfa7296922',
    messagingSenderId: '1099105297287',
    projectId: 'mypresence-prod',
    authDomain: 'mypresence-prod.firebaseapp.com',
    databaseURL:
        'https://mypresence-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMRvCSBe1qjJ1bGMxoHqD1M572lDQ_x4w',
    appId: '1:1099105297287:android:1d72b4cb141dfa6a296922',
    messagingSenderId: '1099105297287',
    projectId: 'mypresence-prod',
    databaseURL:
        'https://mypresence-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMRvCSBe1qjJ1bGMxoHqD1M572lDQ_x4w',
    appId: '1:1099105297287:ios:acb3754a14381b40296922',
    messagingSenderId: '1099105297287',
    projectId: 'mypresence-prod',
    databaseURL:
        'https://mypresence-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-prod.firebasestorage.app',
    iosBundleId: 'com.mypresence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMRvCSBe1qjJ1bGMxoHqD1M572lDQ_x4w',
    appId: '1:1099105297287:ios:acb3754a14381b40296922',
    messagingSenderId: '1099105297287',
    projectId: 'mypresence-prod',
    databaseURL:
        'https://mypresence-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-prod.firebasestorage.app',
    iosBundleId: 'com.mypresence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMRvCSBe1qjJ1bGMxoHqD1M572lDQ_x4w',
    appId: '1:1099105297287:web:544b5af3ac0acfa7296922',
    messagingSenderId: '1099105297287',
    projectId: 'mypresence-prod',
    authDomain: 'mypresence-prod.firebaseapp.com',
    databaseURL:
        'https://mypresence-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-prod.firebasestorage.app',
  );
}
