// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXHZ_pri4MYjuS0PehuGOiOe4FLCSGDU',
    appId: '1:911576285238:web:ffb8f7fa90396016cf5897',
    messagingSenderId: '911576285238',
    projectId: 'mypresence-db',
    authDomain: 'mypresence-db.firebaseapp.com',
    databaseURL:
        'https://mypresence-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBul0726wptj6rG3_Q_TSCKl99ajdlb-SI',
    appId: '1:911576285238:android:cb4bce033e9d6b80cf5897',
    messagingSenderId: '911576285238',
    projectId: 'mypresence-db',
    databaseURL:
        'https://mypresence-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxXHZ_pri4MYjuS0PehuGOiOe4FLCSGDU',
    appId: '1:911576285238:ios:ffb8f7fa90396016cf5897',
    messagingSenderId: '911576285238',
    projectId: 'mypresence-db',
    databaseURL:
        'https://mypresence-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-db.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxXHZ_pri4MYjuS0PehuGOiOe4FLCSGDU',
    appId: '1:911576285238:ios:ffb8f7fa90396016cf5897',
    messagingSenderId: '911576285238',
    projectId: 'mypresence-db',
    databaseURL:
        'https://mypresence-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxXHZ_pri4MYjuS0PehuGOiOe4FLCSGDU',
    appId: '1:911576285238:web:ffb8f7fa90396016cf5897',
    messagingSenderId: '911576285238',
    projectId: 'mypresence-db',
    authDomain: 'mypresence-db.firebaseapp.com',
    databaseURL:
        'https://mypresence-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mypresence-db.firebasestorage.app',
    measurementId: 'G-SRL5QS4CCB',
  );
}
