// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO2Zv_Yz4cxPIVdH18dGxS3HVKiIRvbc0',
    appId: '1:112547967654:web:9fe43de206bda7da237a67',
    messagingSenderId: '112547967654',
    projectId: 'inventory-410f4',
    authDomain: 'inventory-410f4.firebaseapp.com',
    databaseURL:
        'https://inventory-410f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventory-410f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyx1X14ZL9NM9plEHPrLiFxFgbHj3iTvE',
    appId: '1:112547967654:android:c862030a1105b4b2237a67',
    messagingSenderId: '112547967654',
    projectId: 'inventory-410f4',
    databaseURL:
        'https://inventory-410f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventory-410f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvRB_6gYftQ5VSkBPzL0e4DnTRbRFeK8',
    appId: '1:112547967654:ios:bbd9445014336057237a67',
    messagingSenderId: '112547967654',
    projectId: 'inventory-410f4',
    databaseURL:
        'https://inventory-410f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventory-410f4.firebasestorage.app',
    iosClientId:
        '112547967654-gfoaflr90n42c2m3pgft8sid9ep4nhhv.apps.googleusercontent.com',
    iosBundleId: 'com.mypresence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvRB_6gYftQ5VSkBPzL0e4DnTRbRFeK8',
    appId: '1:112547967654:ios:bbd9445014336057237a67',
    messagingSenderId: '112547967654',
    projectId: 'inventory-410f4',
    databaseURL:
        'https://inventory-410f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventory-410f4.firebasestorage.app',
    iosClientId:
        '112547967654-gfoaflr90n42c2m3pgft8sid9ep4nhhv.apps.googleusercontent.com',
    iosBundleId: 'com.mypresence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO2Zv_Yz4cxPIVdH18dGxS3HVKiIRvbc0',
    appId: '1:112547967654:web:9601b3649980091a237a67',
    messagingSenderId: '112547967654',
    projectId: 'inventory-410f4',
    authDomain: 'inventory-410f4.firebaseapp.com',
    databaseURL:
        'https://inventory-410f4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'inventory-410f4.firebasestorage.app',
    measurementId: 'G-XN0DW6D60V',
  );
}
